apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-claim
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce  # This matches your PVC's access mode
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath  # This should match the PVC's storageClassName (if specified)
  hostPath:
    path: var/opt/mssql/data  # Path on the host machine where the data will be stored
